config/routes.rb
Rails.application.routes.draw do
  resources :plastics
  resources :people
  resources :irons
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/iron.rb
class Iron < ApplicationRecord
end

app/controllers/irons_controller.rb
class IronsController < ApplicationController
  before_action :set_iron, only: %i[ show edit update destroy ]

  # GET /irons or /irons.json
  def index
    @irons = Iron.all
  end

  # GET /irons/1 or /irons/1.json
  def show
  end

  # GET /irons/new
  def new
    @iron = Iron.new
  end

  # GET /irons/1/edit
  def edit
  end

  # POST /irons or /irons.json
  def create
    @iron = Iron.new(iron_params)

    respond_to do |format|
      if @iron.save
        format.html { redirect_to @iron, notice: "Iron was successfully created." }
        format.json { render :show, status: :created, location: @iron }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @iron.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /irons/1 or /irons/1.json
  def update
    respond_to do |format|
      if @iron.update(iron_params)
        format.html { redirect_to @iron, notice: "Iron was successfully updated." }
        format.json { render :show, status: :ok, location: @iron }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @iron.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /irons/1 or /irons/1.json
  def destroy
    @iron.destroy
    respond_to do |format|
      format.html { redirect_to irons_url, notice: "Iron was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iron
      @iron = Iron.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def iron_params
      params.require(:iron).permit(:name, :type)
    end
end

app/helpers/irons_helper.rb
module IronsHelper
end

app/views/irons/_form.html.erb
<%= form_with(model: iron) do |form| %>
  <% if iron.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iron.errors.count, "error") %> prohibited this iron from being saved:</h2>

      <ul>
        <% iron.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/irons/edit.html.erb
<h1>Editing Iron</h1>

<%= render 'form', iron: @iron %>

<%= link_to 'Show', @iron %> |
<%= link_to 'Back', irons_path %>

app/views/irons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Irons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @irons.each do |iron| %>
      <tr>
        <td><%= iron.name %></td>
        <td><%= iron.type %></td>
        <td><%= link_to 'Show', iron %></td>
        <td><%= link_to 'Edit', edit_iron_path(iron) %></td>
        <td><%= link_to 'Destroy', iron, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iron', new_iron_path %>

app/views/irons/new.html.erb
<h1>New Iron</h1>

<%= render 'form', iron: @iron %>

<%= link_to 'Back', irons_path %>

app/views/irons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @iron.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @iron.type %>
</p>

<%= link_to 'Edit', edit_iron_path(@iron) %> |
<%= link_to 'Back', irons_path %>