config/routes.rb
Rails.application.routes.draw do
  resources :plastics
  resources :people
  resources :irons
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plastic.rb
class Plastic < ApplicationRecord
end

app/controllers/plastics_controller.rb
class PlasticsController < ApplicationController
  before_action :set_plastic, only: %i[ show edit update destroy ]

  # GET /plastics or /plastics.json
  def index
    @plastics = Plastic.all
  end

  # GET /plastics/1 or /plastics/1.json
  def show
  end

  # GET /plastics/new
  def new
    @plastic = Plastic.new
  end

  # GET /plastics/1/edit
  def edit
  end

  # POST /plastics or /plastics.json
  def create
    @plastic = Plastic.new(plastic_params)

    respond_to do |format|
      if @plastic.save
        format.html { redirect_to @plastic, notice: "Plastic was successfully created." }
        format.json { render :show, status: :created, location: @plastic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plastic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plastics/1 or /plastics/1.json
  def update
    respond_to do |format|
      if @plastic.update(plastic_params)
        format.html { redirect_to @plastic, notice: "Plastic was successfully updated." }
        format.json { render :show, status: :ok, location: @plastic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plastic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plastics/1 or /plastics/1.json
  def destroy
    @plastic.destroy
    respond_to do |format|
      format.html { redirect_to plastics_url, notice: "Plastic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plastic
      @plastic = Plastic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plastic_params
      params.require(:plastic).permit(:name, :type)
    end
end

app/helpers/plastics_helper.rb
module PlasticsHelper
end

app/views/plastics/_form.html.erb
<%= form_with(model: plastic) do |form| %>
  <% if plastic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plastic.errors.count, "error") %> prohibited this plastic from being saved:</h2>

      <ul>
        <% plastic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plastics/edit.html.erb
<h1>Editing Plastic</h1>

<%= render 'form', plastic: @plastic %>

<%= link_to 'Show', @plastic %> |
<%= link_to 'Back', plastics_path %>

app/views/plastics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plastics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plastics.each do |plastic| %>
      <tr>
        <td><%= plastic.name %></td>
        <td><%= plastic.type %></td>
        <td><%= link_to 'Show', plastic %></td>
        <td><%= link_to 'Edit', edit_plastic_path(plastic) %></td>
        <td><%= link_to 'Destroy', plastic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plastic', new_plastic_path %>

app/views/plastics/new.html.erb
<h1>New Plastic</h1>

<%= render 'form', plastic: @plastic %>

<%= link_to 'Back', plastics_path %>

app/views/plastics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plastic.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @plastic.type %>
</p>

<%= link_to 'Edit', edit_plastic_path(@plastic) %> |
<%= link_to 'Back', plastics_path %>